import { Inter } from 'next/font/google';

import { ThemeProvider } from '@/providers/theme';

import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

// @todo: replace metadata export with constants from a config file
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={inter.variable} suppressHydrationWarning>
      <body className='overflow-y-scroll antialiased'>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
